### ISSUE TITLE
Show line numbers while writing PEG.js grammar Online

### ISSUE THREAD

**Issue by djadmin** [pegjs/website#12]
I'd be very great if we could show line numbers in the Grammar writing section (```<textarea>```)  at http://pegjs.majda.cz/online.

When we write grammar directly into the online editor and if any error occurs in the grammar it shows respective line number. But to find the line number we need to copy the code in the text editor and check the line number where exactly the error is. I feel it's not easy to debug there.

PS: I'd like  take this up but need prior discussion before implementing.

**Comment by dmajda** [comment]
Agreed, this would be useful.

The best course of action to fix this would be to replace the `<textarea>` with an editor such as [CodeMirror](https://codemirror.net/). This is something I want to do for a long time, just did’t get around to actually do it because of more important things. A patch would be welcome.

**Comment by djadmin** [comment]
Hi,

I've embedded CodeMirror in online version of Pegjs website. Please review the code and working demo of CodeMirror inside pegjs website here

#DEMO#: http://pegjs-website.herokuapp.com/online 

Code : https://github.com/djadmin/website/commit/cc2179083c458e1c80e4aebf081e7d7a9d515feb

Once you review and accept the feature, I can send you the pull request. Hope that is fine procedure to do it.

Ps: There are 2 issues which has to be fixed (related to CSS in CodeMirror editor). I'm on it.

Thank you
